version: "2"
services:
  resume:
    image: "repo.1000m.xin/public/node:latest"
    container_name: "resume"
    user: "root"
    working_dir: /home/node/app
    volumes:
      - ./resume:/home/node/app
    ports:
      - "8081:8080"
    command: "npm run dev"
#networks:
 # default:
   # external:
   #   name: network
